# Introduction to PyTorch

> Torch Webpage: https://pytorch.org/

> Further Reading: https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html

In [12]:
import torch
import numpy as np

In [2]:
# Set a seed for reproducibility
torch.manual_seed(7)

### Tensors

In [6]:
# A tensor, randomly initialized.
num_rows = 5
num_cols = 5
tensor_a = torch.randn((num_rows, num_cols))

In [7]:
print(tensor_a)

tensor([[ 0.5722,  0.3078, -0.1259, -0.9578,  1.7518],
        [ 0.9796,  0.4105,  1.7675,  0.7569,  0.6460],
        [ 0.0756, -0.1525,  0.1958, -1.5688, -1.1247],
        [-0.3144,  0.6260,  0.6403,  0.6839,  1.6132],
        [ 0.9332, -0.9772, -0.8160,  1.1565, -1.2107]])


In [8]:
# A tensor, uninitialized (values populated are those already in the memory locatio nallocated.)
num_rows = 5
num_cols = 5
tensor_a = torch.empty((num_rows, num_cols))

In [9]:
print(tensor_a)

tensor([[ 5.1655e-25,  4.5706e-41,  5.1655e-25,  4.5706e-41,  4.4842e-44],
        [ 0.0000e+00,  1.5695e-43,  0.0000e+00,  5.6699e-37,  0.0000e+00],
        [ 1.5695e-43,  0.0000e+00,  5.6442e-37,  0.0000e+00,  5.1655e-25],
        [ 4.5706e-41,  6.5776e-38,  0.0000e+00,  4.2039e-45,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  1.4013e-45,  0.0000e+00, -9.0657e-32]])


In [10]:
# A tensor, filled with zeros
num_rows = 5
num_cols = 5
tensor_a = torch.zeros((num_rows, num_cols))

In [11]:
print(tensor_a)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [14]:
# Change dtype to int32
tensor_a = torch.zeros((num_rows, num_cols), dtype=torch.int32)
print(tensor_a)

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int32)


In [27]:
# Convert list or array to tensor
tensor_a = torch.tensor([[1,2], [3,4]], dtype=torch.float32)
tensor_b = torch.tensor([[0,7], [5,6]], dtype=torch.float32)

### Tensor Ops

In [28]:
# Elementwise product of tensors
tensor_a * tensor_b

tensor([[ 0., 14.],
        [15., 24.]])

In [32]:
# Matrix product
tensor_a @ tensor_b

tensor([[10., 19.],
        [20., 45.]])

In [30]:
# Exponent Power
torch.exp(tensor_a)

tensor([[ 2.7183,  7.3891],
        [20.0855, 54.5981]])

In [31]:
# Square Root
torch.sqrt(tensor_a)

tensor([[1.0000, 1.4142],
        [1.7321, 2.0000]])