# Introduction to PyTorch

> Torch Webpage: https://pytorch.org/

> Further Reading: https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html

In [1]:
import torch
import numpy as np

In [2]:
# Set a seed for reproducibility
torch.manual_seed(7)

### Tensors

In [3]:
# A tensor, randomly initialized.
num_rows = 5
num_cols = 5
tensor_a = torch.randn((num_rows, num_cols))

In [4]:
print(tensor_a)

tensor([[-0.8201,  0.3956,  0.8989, -1.3884, -0.1670],
        [ 0.2851, -0.6411, -0.8937,  0.9265, -1.2169],
        [-0.0810,  1.3615, -1.3032,  0.0875, -1.3850],
        [ 0.5036, -0.0835, -0.5640, -2.0565, -0.3567],
        [ 1.0956,  0.4824,  1.3989,  1.4059, -1.4013]])


In [5]:
# A tensor, uninitialized (values populated are those already in the memory locatio nallocated.)
num_rows = 5
num_cols = 5
tensor_a = torch.empty((num_rows, num_cols))

In [6]:
print(tensor_a)

tensor([[1.7753e+28, 4.4339e+27, 5.6719e-11, 7.3471e+28, 2.6383e+23],
        [2.7376e+20, 1.8040e+28, 1.8750e-19, 7.3909e+22, 2.4176e-12],
        [2.6209e+20, 4.1641e+12, 8.9625e-01, 7.9309e+34, 7.9439e+08],
        [3.2604e-12, 7.3113e+34, 9.5492e-01, 7.3154e+34, 5.9682e-02],
        [7.0374e+22, 5.7886e+22, 6.7120e+22, 6.7331e+22, 6.7120e+22]])


In [7]:
# A tensor, filled with zeros
num_rows = 5
num_cols = 5
tensor_a = torch.zeros((num_rows, num_cols))

In [8]:
print(tensor_a)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [9]:
# Change dtype to int32
tensor_a = torch.zeros((num_rows, num_cols), dtype=torch.int32)
print(tensor_a)

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int32)


In [10]:
# Convert list or array to tensor
tensor_a = torch.tensor([[1,2], [3,4]], dtype=torch.float32)
tensor_b = torch.tensor([[0,7], [5,6]], dtype=torch.float32)

### Tensor Ops

In [11]:
# Elementwise product of tensors
tensor_a * tensor_b

tensor([[ 0., 14.],
        [15., 24.]])

In [12]:
# Matrix product
tensor_a @ tensor_b

tensor([[10., 19.],
        [20., 45.]])

In [13]:
# Exponent Power
torch.exp(tensor_a)

tensor([[ 2.7183,  7.3891],
        [20.0855, 54.5982]])

In [14]:
# Square Root
torch.sqrt(tensor_a)

tensor([[1.0000, 1.4142],
        [1.7321, 2.0000]])

As per https://pytorch.org/docs/stable/generated/torch.mm.html, the torch.mm API will do matrix multiplications as well!

In [15]:
tensor_a.mm(tensor_b)

tensor([[10., 19.],
        [20., 45.]])